<?php

namespace ContainerSU1otBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YFykU57Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yFykU57' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yFykU57'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['privates', '.errored..service_locator.yFykU57.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.yFykU57": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
            'ficheFraisRepository' => ['privates', 'App\\Repository\\FicheFraisRepository', 'getFicheFraisRepositoryService', true],
        ], [
            'entityManager' => 'Doctrine\\ORM\\EntityManager',
            'ficheFraisRepository' => 'App\\Repository\\FicheFraisRepository',
        ]);
    }
}
