<?php

namespace ContainerC3wawGq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jj8vsi9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jj8vsi9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jj8vsi9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ficheFraisRepository' => ['privates', 'App\\Repository\\FicheFraisRepository', 'getFicheFraisRepositoryService', true],
            'ligneFraisForfaitRepository' => ['privates', 'App\\Repository\\LigneFraisForfaitRepository', 'getLigneFraisForfaitRepositoryService', true],
            'ligneFraisHorsForfaitRepository' => ['privates', 'App\\Repository\\LigneFraisForfaitRepository', 'getLigneFraisForfaitRepositoryService', true],
        ], [
            'ficheFraisRepository' => 'App\\Repository\\FicheFraisRepository',
            'ligneFraisForfaitRepository' => 'App\\Repository\\LigneFraisForfaitRepository',
            'ligneFraisHorsForfaitRepository' => 'App\\Repository\\LigneFraisForfaitRepository',
        ]);
    }
}
