<?php

namespace ContainerC3wawGq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YsmFcWQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ysmFcWQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ysmFcWQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'compt' => ['privates', '.errored..service_locator.ysmFcWQ.App\\Entity\\Comptable', NULL, 'Cannot autowire service ".service_locator.ysmFcWQ": it references class "App\\Entity\\Comptable" but no such service exists.'],
        ], [
            'authenticationUtils' => '?',
            'compt' => 'App\\Entity\\Comptable',
        ]);
    }
}
