<?php

namespace Container2N9jxo1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X2i2iKNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X2i2iKN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X2i2iKN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'visiteur' => ['privates', '.errored..service_locator.X2i2iKN.App\\Entity\\Visiteur', NULL, 'Cannot autowire service ".service_locator.X2i2iKN": it references class "App\\Entity\\Visiteur" but no such service exists.'],
        ], [
            'visiteur' => 'App\\Entity\\Visiteur',
        ]);
    }
}
