<?php

namespace Container2N9jxo1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X2i2iKN.App\Entity\Visiteur' shared service.
     *
     * @return \App\Entity\Visiteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.X2i2iKN": it references class "App\\Entity\\Visiteur" but no such service exists.');
    }
}
