<?php

namespace ContainerCe3IBvn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z1pbfDWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z1pbfDW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z1pbfDW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FicheFraisController::renseigner' => ['privates', '.service_locator.dmVoI.T', 'get_ServiceLocator_DmVoI_TService', true],
            'App\\Controller\\FicheFraisController::visualiser' => ['privates', '.service_locator.8IrENBR', 'get_ServiceLocator_8IrENBRService', true],
            'App\\Controller\\LoginController::comptable' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController::visiteur' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oKYopqz', 'get_ServiceLocator_OKYopqzService', true],
            'App\\Controller\\VisiteurController::delete' => ['privates', '.service_locator.biCdold', 'get_ServiceLocator_BiCdoldService', true],
            'App\\Controller\\VisiteurController::edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\VisiteurController::index' => ['privates', '.service_locator.6lpdq4M', 'get_ServiceLocator_6lpdq4MService', true],
            'App\\Controller\\VisiteurController::new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\VisiteurController::show' => ['privates', '.service_locator.X2i2iKN', 'get_ServiceLocator_X2i2iKNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FicheFraisController:renseigner' => ['privates', '.service_locator.dmVoI.T', 'get_ServiceLocator_DmVoI_TService', true],
            'App\\Controller\\FicheFraisController:visualiser' => ['privates', '.service_locator.8IrENBR', 'get_ServiceLocator_8IrENBRService', true],
            'App\\Controller\\LoginController:comptable' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController:visiteur' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oKYopqz', 'get_ServiceLocator_OKYopqzService', true],
            'App\\Controller\\VisiteurController:delete' => ['privates', '.service_locator.biCdold', 'get_ServiceLocator_BiCdoldService', true],
            'App\\Controller\\VisiteurController:edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\VisiteurController:index' => ['privates', '.service_locator.6lpdq4M', 'get_ServiceLocator_6lpdq4MService', true],
            'App\\Controller\\VisiteurController:new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\VisiteurController:show' => ['privates', '.service_locator.X2i2iKN', 'get_ServiceLocator_X2i2iKNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FicheFraisController::renseigner' => '?',
            'App\\Controller\\FicheFraisController::visualiser' => '?',
            'App\\Controller\\LoginController::comptable' => '?',
            'App\\Controller\\LoginController::visiteur' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VisiteurController::delete' => '?',
            'App\\Controller\\VisiteurController::edit' => '?',
            'App\\Controller\\VisiteurController::index' => '?',
            'App\\Controller\\VisiteurController::new' => '?',
            'App\\Controller\\VisiteurController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FicheFraisController:renseigner' => '?',
            'App\\Controller\\FicheFraisController:visualiser' => '?',
            'App\\Controller\\LoginController:comptable' => '?',
            'App\\Controller\\LoginController:visiteur' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VisiteurController:delete' => '?',
            'App\\Controller\\VisiteurController:edit' => '?',
            'App\\Controller\\VisiteurController:index' => '?',
            'App\\Controller\\VisiteurController:new' => '?',
            'App\\Controller\\VisiteurController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
