<?php

namespace Container928fpQJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M_Oug6MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M.oug6M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M.oug6M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FicheFraisController::renseigner' => ['privates', '.service_locator.Wbb3jTR', 'get_ServiceLocator_Wbb3jTRService', true],
            'App\\Controller\\FicheFraisController::visualiser' => ['privates', '.service_locator.xkzR_pl', 'get_ServiceLocator_XkzRPlService', true],
            'App\\Controller\\LoginController::comptable' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController::visiteur' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oKYopqz', 'get_ServiceLocator_OKYopqzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FicheFraisController:renseigner' => ['privates', '.service_locator.Wbb3jTR', 'get_ServiceLocator_Wbb3jTRService', true],
            'App\\Controller\\FicheFraisController:visualiser' => ['privates', '.service_locator.xkzR_pl', 'get_ServiceLocator_XkzRPlService', true],
            'App\\Controller\\LoginController:comptable' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController:visiteur' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oKYopqz', 'get_ServiceLocator_OKYopqzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FicheFraisController::renseigner' => '?',
            'App\\Controller\\FicheFraisController::visualiser' => '?',
            'App\\Controller\\LoginController::comptable' => '?',
            'App\\Controller\\LoginController::visiteur' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FicheFraisController:renseigner' => '?',
            'App\\Controller\\FicheFraisController:visualiser' => '?',
            'App\\Controller\\LoginController:comptable' => '?',
            'App\\Controller\\LoginController:visiteur' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
