<?php

namespace ContainerOf75H83;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KwPFVMUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kwPFVMU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kwPFVMU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FicheFraisController::renseigner' => ['privates', '.service_locator.Wbb3jTR', 'get_ServiceLocator_Wbb3jTRService', true],
            'App\\Controller\\FicheFraisController::valider' => ['privates', '.service_locator.RRxxsY4', 'get_ServiceLocator_RRxxsY4Service', true],
            'App\\Controller\\FicheFraisController::visualiser' => ['privates', '.service_locator.UIbAps0', 'get_ServiceLocator_UIbAps0Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\RegistrationController::registerComptable' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oKYopqz', 'get_ServiceLocator_OKYopqzService', true],
            'App\\Controller\\SecurityController::loginComptable' => ['privates', '.service_locator.ysmFcWQ', 'get_ServiceLocator_YsmFcWQService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FicheFraisController:renseigner' => ['privates', '.service_locator.Wbb3jTR', 'get_ServiceLocator_Wbb3jTRService', true],
            'App\\Controller\\FicheFraisController:valider' => ['privates', '.service_locator.RRxxsY4', 'get_ServiceLocator_RRxxsY4Service', true],
            'App\\Controller\\FicheFraisController:visualiser' => ['privates', '.service_locator.UIbAps0', 'get_ServiceLocator_UIbAps0Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\RegistrationController:registerComptable' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oKYopqz', 'get_ServiceLocator_OKYopqzService', true],
            'App\\Controller\\SecurityController:loginComptable' => ['privates', '.service_locator.ysmFcWQ', 'get_ServiceLocator_YsmFcWQService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FicheFraisController::renseigner' => '?',
            'App\\Controller\\FicheFraisController::valider' => '?',
            'App\\Controller\\FicheFraisController::visualiser' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::registerComptable' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::loginComptable' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FicheFraisController:renseigner' => '?',
            'App\\Controller\\FicheFraisController:valider' => '?',
            'App\\Controller\\FicheFraisController:visualiser' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:registerComptable' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:loginComptable' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
