<?php

namespace ContainerOf75H83;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFraisHorsForfaitTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FraisHorsForfaitType' shared autowired service.
     *
     * @return \App\Form\FraisHorsForfaitType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FraisHorsForfaitType.php';

        return $container->privates['App\\Form\\FraisHorsForfaitType'] = new \App\Form\FraisHorsForfaitType();
    }
}
