controllers:
    resource: ../src/Controller/
    type: attribute

app_accueil:
    path: /
    controller: App\Controller\LoginController::visiteur

app_comptable:
    path: /comptable
    controller: App\Controller\LoginController::comptable

app_home:
    path: /home
    controller: App\Controller\AccueilController::index

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

app_frais_forfait:
    path: /frais/forfait
    controller: App\Controller\FicheFraisController::renseigner

app_frais_hors_forfait:
    path: /frais/hors/forfait
    controller: App\Controller\FicheFraisController::renseignerHorsForfait

app_visu_frais:
    path: /fiche/frais/visualiser
    controller: App\Controller\FicheFraisController::visualiser
    methods: [GET]

