controllers:
    resource: ../src/Controller/
    type: attribute

#-------------------------
# AccueilController
#-------------------------

# Accueil #
app_home:
    path: /home
    controller: App\Controller\AccueilController::accueilVisiteur

app_home_comptable:
    path: /home/comptable
    controller: App\Controller\AccueilController::accueilComptable

#-------------------------
# LoginController
#-------------------------

app_visiteur:
    path: /
    controller: App\Controller\LoginController::visiteur

app_comptable:
    path: /comptable
    controller: App\Controller\LoginController::comptable

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

#-------------------------
# FicheFraisController
#-------------------------

app_renseigner_frais:
    path: /renseigner/frais
    controller: App\Controller\FicheFraisController::renseigner

app_visu_frais:
    path: /visualiser/frais
    controller: App\Controller\FicheFraisController::visualiser

