<?php

namespace ContainerFFRZzce;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.biCdold.App\Entity\Visiteur' shared service.
     *
     * @return \App\Entity\Visiteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.biCdold": it references class "App\\Entity\\Visiteur" but no such service exists.');
    }
}
