<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5i1zxtM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5i1zxtM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5i1zxtM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5i1zxtM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5i1zxtM\App_KernelDevDebugContainer([
    'container.build_hash' => '5i1zxtM',
    'container.build_id' => 'd72109e8',
    'container.build_time' => 1676627683,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5i1zxtM');
