<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYOrsdxy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYOrsdxy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYOrsdxy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYOrsdxy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYOrsdxy\App_KernelDevDebugContainer([
    'container.build_hash' => 'YOrsdxy',
    'container.build_id' => '65ed2725',
    'container.build_time' => 1666036112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYOrsdxy');
