<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCe3IBvn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCe3IBvn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCe3IBvn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCe3IBvn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCe3IBvn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ce3IBvn',
    'container.build_id' => 'bee0edbf',
    'container.build_time' => 1670963959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCe3IBvn');
