<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_register_comptable' => [[], ['_controller' => 'App\\Controller\\RegistrationController::registerComptable'], [], [['text', '/register/comptable']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_login_comptable' => [[], ['_controller' => 'App\\Controller\\SecurityController::loginComptable'], [], [['text', '/loginComptable']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\AccueilController::accueilVisiteur'], [], [['text', '/home']], [], [], []],
    'app_home_comptable' => [[], ['_controller' => 'App\\Controller\\AccueilController::accueilComptable'], [], [['text', '/home/comptable']], [], [], []],
    'app_visiteur' => [[], ['_controller' => 'App\\Controller\\LoginController::visiteur'], [], [['text', '/']], [], [], []],
    'app_comptable' => [[], ['_controller' => 'App\\Controller\\LoginController::comptable'], [], [['text', '/comptable']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_renseigner_frais' => [[], ['_controller' => 'App\\Controller\\FicheFraisController::renseigner'], [], [['text', '/renseigner/frais']], [], [], []],
    'app_visu_frais' => [[], ['_controller' => 'App\\Controller\\FicheFraisController::visualiser'], [], [['text', '/visualiser/frais']], [], [], []],
    'app_choix_validation_frais' => [[], ['_controller' => 'App\\Controller\\FicheFraisController::choixValidation'], [], [['text', '/comptable/choixValidation/frais']], [], [], []],
    'app_valider_frais' => [[], ['_controller' => 'App\\Controller\\FicheFraisController::valider'], [], [['text', '/comptable/valider/frais']], [], [], []],
];
