<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/826.591cd6cc.js',
                '/build/app.1594675d.js',
            ],
            'css' => [
                '/build/app.31d6cfe0.css',
            ],
        ],
    ],
],

]];
